version: '3'
services:
  demo-page-dev:
    image: 'coai:latest'
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    user: root
    command: npm run dev
    working_dir: /home/node/dev
    ports:
      - 18080:8080
    volumes:
      - .:/home/node/dev:rw